### PR TITLE
Complete the attachment processors extension

### LINKED ISSUE #2379: Possible confusing logging on ProxyOperationManager.cs
Usually when we've some issue with coverlet msbuild or .NET tool driver we enable logging to understand if vstest plat killed process after famous 100ms.
BTW seem that logging is wrong and also in case of clean shutdown timeout log is emitted

https://github.com/microsoft/vstest/blob/d10bcbb28cc3999bcc12758a41a04b998eb9595b/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs#L202-L236

I think that log emitted in line 228 should be emitted only if `testHostExited` event was not signaled.

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Complete attachment processors extension

fixes https://github.com/microsoft/vstest/issues/2379

Missing part unrelated to this repo:
* Update documentation for attachment processor discovery
* Move coverage attachment processor to coverage repo
* VS integration

contributes to https://github.com/microsoft/vstest/issues/1811

### CODE REVIEW

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+        private const string CoverageFriendlyName = "Code Coverage";
+
+        public IReadOnlyDictionary<string, IConfigurableDataCollectorAttachmentProcessor> Create(InvokedDataCollector[] invokedDataCollectors)
+        {
+            IDictionary<string, Tuple<string, IConfigurableDataCollectorAttachmentProcessor>> datacollectorsAttachmentsProcessors = new Dictionary<string, Tuple<string, IConfigurableDataCollectorAttachmentProcessor>>();
+            bool addCodeCoverageAttachmentProcessors = true;
+
+            if (invokedDataCollectors != null)
+            {
+                // We order files by filename descending so in case of the same collector from the same nuget but with different versions, we'll run the newer version.
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:27]: > We order files by filename descending so in case of the same collector from the same nuget but with different versions, we'll run the newer version. [](http://example.com/codeflow?start=18&length=149)

When would this normally happen? (where we have different version of coverlet referenced)
Is this across projects in the solution?

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+                // i.e. C:\Users\xxx\.nuget\packages\coverlet.collector
+                // /3.0.2
+                // /3.0.3
+                // /3.1.0
+                foreach (var invokedDataCollector in invokedDataCollectors.OrderByDescending(d => d.FilePath))
+                {
+                    EqtTrace.Info($"DataCollectorAttachmentsProcessorsFactory: Analyzing data collector attachment processor Uri: {invokedDataCollector.Uri} AssemblyQualifiedName: {invokedDataCollector.AssemblyQualifiedName} FilePath: {invokedDataCollector.FilePath} HasAttachmentProcessor: {invokedDataCollector.HasAttachmentProcessor}");
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:34]: >AssemblyQualifiedName [](http://example.com/codeflow?start=157&length=21)

What format is this in? Would be nice to add a comment in code. Same for fie path as well.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+
+                    // We'll merge using only one AQN in case of more "same processors" in different assembly.
+                    if (!invokedDataCollector.HasAttachmentProcessor || datacollectorsAttachmentsProcessors.ContainsKey(invokedDataCollector.AssemblyQualifiedName))
+                    {
+                        continue;
+                    }
+
+                    var dataCollectorExtensionManager = DataCollectorExtensionManager.Create(invokedDataCollector.FilePath, TestSessionMessageLogger.Instance);
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:42]: >DataCollectorExtensionManager.Create [](http://example.com/codeflow?start=56&length=36)

Do we cache this within the extension manager today?

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+                    {
+                        Type attachmentProcessorType = ((DataCollectorConfig)dataCollectorExtension.TestPluginInfo).AttachmentsProcessorType;
+                        IConfigurableDataCollectorAttachmentProcessor dataCollectorAttachmentProcessorInstance = null;
+                        try
+                        {
+                            dataCollectorAttachmentProcessorInstance = TestPluginManager.CreateTestExtension<IConfigurableDataCollectorAttachmentProcessor>(attachmentProcessorType);
+                        }
+                        catch (Exception ex)
+                        {
+                            EqtTrace.Error($"DataCollectorAttachmentsProcessorsFactory: Failed during the creation of data collector attachment processor '{attachmentProcessorType.AssemblyQualifiedName}'\n{ex}");
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:54]: >EqtTrace.Error [](http://example.com/codeflow?start=28&length=14)

curious, where do these get printed? Do they go into the test platform diagnostic log file? How about to the output->Tests pane if it is driven through VS...

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+                        }
+
+                        if (dataCollectorAttachmentProcessorInstance != null && !datacollectorsAttachmentsProcessors.ContainsKey(attachmentProcessorType.AssemblyQualifiedName))
+                        {
+                            datacollectorsAttachmentsProcessors.Add(attachmentProcessorType.AssemblyQualifiedName, new Tuple<string, IConfigurableDataCollectorAttachmentProcessor>(dataCollectorExtension.Metadata.FriendlyName, dataCollectorAttachmentProcessorInstance));
+
+                            if (invokedDataCollector.Uri.AbsoluteUri == CoverageUri.AbsoluteUri)
+                            {
+                                EqtTrace.Info($"DataCollectorAttachmentsProcessorsFactory: Attachment data processor for data collector with friendly name '{CoverageFriendlyName}' found '{attachmentProcessorType.AssemblyQualifiedName}' inside '{invokedDataCollector.FilePath}'");
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:63]: >EqtTrace.Info($"DataCollectorAttachmentsProcessorsFactory: Attachment data processor for data collector with friendly name '{CoverageFriendlyName}' found '{attachmentProcessorType.AssemblyQualifiedName}' inside '{invokedDataCollector.FilePath}'"); [](http://example.com/codeflow?start=32&length=247)

hmm, this is interesting. Could we add comments on when this would happen and why we would want to overwrite our default processor if we see an external one with the same uri. Shouldn't we ideally throw and ignore the external one?

File: src/Microsoft.TestPlatform.ObjectModel/InvokedDataCollector.cs [hunk 6]
```diff
@@ -0,0 +1,99 @@
+﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT license. See LICENSE file in the project root for full license information.
+
+using System;
+using System.Runtime.Serialization;
+
+namespace Microsoft.VisualStudio.TestPlatform.ObjectModel
+{
+    public sealed class InvokedDataCollector : IEquatable<InvokedDataCollector>
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.ObjectModel/InvokedDataCollector.cs:9]: >public [](http://example.com/codeflow?start=4&length=6)

Does this need to be public? Can we make it internal?

File: src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+    using System.Collections.Generic;
+    using System.Threading;
+    using System.Threading.Tasks;
+    using System.Xml;
+    using Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging;
+
+    /// <summary>
+    /// Interface for data collectors add-ins that choose to reprocess generated attachments
+    /// </summary>
+    public interface IConfigurableDataCollectorAttachmentProcessor
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs:16]: >IConfigurableDataCollectorAttachmentProcessor [](http://example.com/codeflow?start=21&length=45)

So the one difference between this and the existing `IDataCollectorAttachmentProcessor` interface is that we now pass in the data collector configuration in the ProcessAttachmentSetsAsync method? Do we know if this interface is (or even can be) used by anyone outside? I wonder if we can just change the existing interface if this wasn't usable externally anyway. Also would we need the whole runsettings blob instead of just that data collectors config. Would someone be interested in reading anything in the runconfiguration element for instance?

File: src/Microsoft.TestPlatform.ObjectModel/InvokedDataCollector.cs (hunk 6 above)
Comment (AbhitejJohn) [reply src/Microsoft.TestPlatform.ObjectModel/InvokedDataCollector.cs:9]: Never mind I see that we reference this in other public interfaces.

File: test/TestAssets/AttachmentProcessorDataCollector/TestExtensionTypesAttribute.cs [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+            this.Types = types;
+        }
+
+        public Type[] Types { get; }
+    }
+
+    [AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = true)]
+    internal sealed class TestExtensionTypesV2Attribute : Attribute
+    {
+        public string ExtensionType { get; }
```
Comment (AbhitejJohn) [inline test/TestAssets/AttachmentProcessorDataCollector/TestExtensionTypesAttribute.cs:29]: >ExtensionType [](http://example.com/codeflow?start=22&length=13)

I'm assuming this attribute would make it into the product after a review. Would be nice to add comments and example formats of what each of these signify.

File: src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs [hunk 9]
```diff
@@ -0,0 +1,156 @@
...
+                            {
+                                // Expected ctor shape ctor(string,string,System.Type,Int32)
+                                // [assembly: TestExtensionTypesV2(ExtensionMetadata.ExtensionType, ExtensionMetadata.Uri, typeof(ExtensionImplementation), 1)]
+
+                                // If the parameter kind is string, (middle line in above diagram) then the blob contains
+                                // a SerString – a PackedLen count of bytes, followed by the UTF8 characters.If the
+                                // string is null, its PackedLen has the value 0xFF(with no following characters).If
+                                // the string is empty(“”), then PackedLen has the value 0x00(with no following
+                                // characters).
+                                string extension = valueReader.ReadSerializedString();
```
Comment (AbhitejJohn) [inline src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs:94]: >extension [](http://example.com/codeflow?start=39&length=9)

what are the values that this can take?

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 1 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:27]: Yep if for instance in VS we have more than one project with different version(we're using the coverage collector as use case)  the idea is to use the up to date one.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 2 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:34]: Assembly qualified name is the standard type name format https://docs.microsoft.com/en-us/dotnet/api/system.type.assemblyqualifiedname?view=net-6.0#remarks

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 4 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:54]: They will go to diagnostic files.

> How about to the output->Tests pane if it is driven through VS...

At the moment looks like this messages are not sent to tests pane in VS. I'll verify the output story there.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 5 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:63]: The idea here is the opposite, today we're shipping attachment processor for coverage inside TP. 
Now we're moving the implementation to coverage repo and we won't move on future implementation there. 
So we cannot remove current implementation for back-compat reason but we want to use implementation coming from datacollector if present.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 3 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:42]: Yes this call will cache the extension.

File: src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs (hunk 7 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs:16]: >  wonder if we can just change the existing interface if this wasn't usable externally anyway. 

We cannot update the existing one(we can do addition of new method but looks weird because for the implementer only one out of the two method will be called so it's not clear imo from user perspective) because if we implement new one but we load collector extension inside old SDK hosts we'll throw a missing implementation exception.

> Also would we need the whole runsettings blob instead of just that data collectors config. Would someone be interested in reading anything in the runconfiguration element for instance?

We had this discussion with @jakubch1 and @fhnaseer and we can do it, but again it could look strange from user perspective, inside DataCollector we're flowing only collector section config and not all runsettings so it's a bit asymmetric. And we expect that settings for an attachment processor that is "attached" to specific collector should handle that "context" and so settings should come from datacollector section.

Anyway we're open to discuss this one if you strongly feel the need.

File: test/TestAssets/AttachmentProcessorDataCollector/TestExtensionTypesAttribute.cs (hunk 8 above)
Comment (MarcoRossignoli) [reply test/TestAssets/AttachmentProcessorDataCollector/TestExtensionTypesAttribute.cs:29]: The idea is to "not ship" the attribute inside the object model. 
We will ship the "documentation" of it very similar to what we're doing inside coverlet for code coverage exclusion https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Instrumentation/Instrumenter.cs#L66

In this way we won't risk to ship a version of attribute and in future change the signature and come back to the same "load issue" we have today.

File: src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs (hunk 9 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs:94]: First two value for the attribute are for "future use".
We want to be able in future to understand from the attribute the "type" of extension and the "identifier" for better performance and to avoid to "get the type" if we're searching for a different type of extension(i.e. DataCollector, TestAdapter etc...).
We didn't define yet the precise "type name" for all extensions.

Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs:94]: For now we're using Type and version.

**Review by jakubch1 — APPROVED** [review]

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 3 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs]: We changed here, we cannot cache this extension because in VS scenario if a user for instance update the runsettings we should load and run the new attachment processor.

File: src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs (hunk 7 above)
Comment (jakubch1) [reply src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs:16]: Let's break existing interface as nobody is using it now and regarding runsettings I think we should be consistent and pass only part for this collector. If some additional options are needed we will need to add options to this data collector.

File: src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/DataCollectionResult.cs [hunk 10]
```diff
@@ -0,0 +1,30 @@
...
+
+using Microsoft.VisualStudio.TestPlatform.ObjectModel;
+using System.Collections.ObjectModel;
+
+namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection
+{
+    /// <summary>
+    /// Information returned after data collection.
+    /// </summary>
+    public class DataCollectionResult
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/DataCollectionResult.cs:12]: check if works internals

Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/DataCollectionResult.cs:12]: We cannot, is used by object with public visibility

File: src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestHandler.cs [hunk 11]
```diff
@@ -391,6 +391,14 @@ private void HandleAfterTestRunEnd(Message message)
 
             var attachmentsets = this.dataCollectionManager.SessionEnded(isCancelled);
             var invokedDataCollectors = this.dataCollectionManager.GetInvokedDataCollectors();
+            if (invokedDataCollectors != null && invokedDataCollectors.Count > 0)
+            {
+                foreach (var invokedDataCollector in invokedDataCollectors)
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestHandler.cs:396]: @AbhitejJohn this is the place where we want to send an "object metric"

cc: @jakubch1

File: src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestHandler.cs [hunk 12]
```diff
@@ -391,6 +391,14 @@ private void HandleAfterTestRunEnd(Message message)
...
+                {
+                    this.requestData.MetricsCollection.Add(TelemetryDataConstants.InvokedDataCollector, invokedDataCollector);
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestHandler.cs:398]: @AbhitejJohn this is the place where we want to send an "object metric"

cc: @jakubch1

File: src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs [hunk 13]
```diff
@@ -0,0 +1,191 @@
...
+                    ExtensionType = extensionType;
+                    ExtensionIdentifier = extensionIdentifier;
+                    ExtensionImplementation = extensionImplementation;
+                    Version = version;
+                }
+            }
+        }
+
+    */
+    internal class MetadataReaderExtensionsHelper
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs:43]: TODO: Add units

File: src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestHandler.cs (hunk 12 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestHandler.cs:398]: We won't add telemetry in this PR, we need a better way to send "object data", primitive type are not so useful or easy to query.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 4 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:56]: I've added message logger, it will flow to VS thanks to ITestRunAttachmentsProcessingEventsHandler

File: src/Microsoft.TestPlatform.Common/Interfaces/Engine/IDataCollectorAttachmentsProcessorsFactory.cs [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+    /// </summary>
+    internal interface IDataCollectorAttachmentsProcessorsFactory
+    {
+        /// <summary>
+        /// Creates and return a list of available attachments processor
+        /// </summary>
+        /// <param name="invokedDataCollector">List of invoked data collectors</param>
+        /// <param name="logger">Message logger</param>
+        /// <returns>List of attachments processors</returns>
+        DataCollectorAttachmentProcessor[] Create(InvokedDataCollector[] invokedDataCollectors, IMessageLogger logger);
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/Interfaces/Engine/IDataCollectorAttachmentsProcessorsFactory.cs:22]: `IEnumerable` express deferred evaluation...it means that if you run methods two time you can get different result. Public contract without streaming capabilities should return "immutable" objects of possible.

File: src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginCache.cs [hunk 15]
```diff
@@ -339,28 +342,35 @@ internal IEnumerable<string> DefaultExtensionPaths
...
             }
+            else
+            {
+                // Check if extensions from this assembly have already been discovered.
+                var extensions = this.TestExtensions?.GetExtensionsDiscoveredFromAssembly<TPluginInfo>(
+                    this.TestExtensions.GetTestExtensionCache<TPluginInfo>(),
+                    extensionAssembly);
 
-            var pluginInfos = this.GetTestExtensions<TPluginInfo, TExtension>(new List<string>() { extensionAssembly });
+                if (extensions != null && extensions.Count > 0)
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginCache.cs:358]: Discussed offline

File: src/Microsoft.TestPlatform.Common/PublicAPI/PublicAPI.Shipped.txt [hunk 16]
```diff
@@ -9,20 +9,17 @@ const Microsoft.VisualStudio.TestPlatform.Common.TestPlatformDefaults.EnableBoun
...
 Microsoft.VisualStudio.TestPlatform.Common.DataCollection.BeforeTestRunStartResult
 Microsoft.VisualStudio.TestPlatform.Common.DataCollection.BeforeTestRunStartResult.BeforeTestRunStartResult(System.Collections.Generic.IDictionary<string, string> environmentVariables, int dataCollectionEventsPort) -> void
 Microsoft.VisualStudio.TestPlatform.Common.DataCollection.BeforeTestRunStartResult.DataCollectionEventsPort.get -> int
 Microsoft.VisualStudio.TestPlatform.Common.DataCollection.BeforeTestRunStartResult.EnvironmentVariables.get -> System.Collections.Generic.IDictionary<string, string>
 Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException
 Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException.InvalidLoggerException(string message) -> void
 Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException.InvalidLoggerException(string message, System.Exception innerException) -> void
-Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.DataCollectorMetadata
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/PublicAPI/PublicAPI.Shipped.txt:22]: Will revert

File: src/Microsoft.TestPlatform.Common/Telemetry/TelemetryDataConstants.cs [hunk 17]
```diff
@@ -26,6 +26,8 @@ public static class TelemetryDataConstants
 
         public static string DataCollectorsEnabled = "VS.TestRun.DataCollectorsEnabled";
 
+        internal const string InvokedDataCollectors = "VS.TestRun.InvokedDataCollectors";
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/Telemetry/TelemetryDataConstants.cs:29]: Thanks will check how to classify

File: src/Microsoft.TestPlatform.Common/ExtensionFramework/DataCollectionExtensionManager.cs [hunk 18]
```diff
@@ -51,20 +51,45 @@ internal class DataCollectorExtensionManager : TestExtensionManager<DataCollecto
...
+
+            return new DataCollectorExtensionManager(unfilteredTestExtensions, filteredTestExtensions, messageLogger);
+        }
     }
 
     /// <summary>
     /// Hold data about the Data Collector.
     /// </summary>
-    public class DataCollectorMetadata : IDataCollectorCapabilities
+    internal class DataCollectorMetadata : IDataCollectorCapabilities
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/ExtensionFramework/DataCollectionExtensionManager.cs:92]: I will revert, tests run but actually I don't know if are used around by someone also if are our internal services.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/TestRunAttachmentsProcessingManager.cs [hunk 19]
```diff
@@ -8,63 +8,64 @@
...
 using Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging;
+using Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities;
 
 namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestRunAttachmentsProcessing
 {
     /// <summary>
     /// Orchestrates test run attachments processing operations.
     /// </summary>
-    public class TestRunAttachmentsProcessingManager : ITestRunAttachmentsProcessingManager
+    internal class TestRunAttachmentsProcessingManager : ITestRunAttachmentsProcessingManager
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/TestRunAttachmentsProcessingManager.cs:25]: Like the above, it's internal implementation not used around because attachment processor is new and until this PR is not possible for users register an attachment processor, but I agree that we can start to cleanup public api with more numbers in follow-up PRs

File: src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs [hunk 20]
```diff
@@ -158,25 +158,48 @@ private void AddKnownExtensions(ref IEnumerable<string> extensionPaths)
...
+                var typesToLoad = TypesToLoadUtilities.GetTypesToLoad(assembly);
+                if (typesToLoad?.Any() == true)
+                {
+                    types.AddRange(typesToLoad);
+                }
 
                 if (!types.Any())
                 {
-                    types = assembly.GetTypes().Where(type => type.GetTypeInfo().IsClass && !type.GetTypeInfo().IsAbstract);
+                    types.AddRange(assembly.GetTypes().Where(type => type.GetTypeInfo().IsClass && !type.GetTypeInfo().IsAbstract));
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs:192]: Yep, this update is needed for the new "versioning" attribute.

File: src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs [hunk 21]
```diff
@@ -0,0 +1,190 @@
...
+    using System.Reflection;
+    using System.Reflection.Metadata;
+    using System.Reflection.PortableExecutable;
+    using System.Text;
+
+    using Microsoft.VisualStudio.TestPlatform.ObjectModel;
+
+    /* Expected attribute shape
+
+        namespace Microsoft.VisualStudio.TestPlatform
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs:20]: I took a deeper look and the namespace is needed because we're searching for it , so I think it's good have a copy/paste sample.

```cs
private const string TestExtensionTypesAttributeV2 = "Microsoft.VisualStudio.TestPlatform.TestExtensionTypesV2Attribute";
```

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/TestRunAttachmentsProcessingManager.cs [hunk 22]
```diff
@@ -91,52 +92,87 @@ private async Task<Collection<AttachmentSet>> InternalProcessTestRunAttachmentsA
             {
                 EqtTrace.Error("TestRunAttachmentsProcessingManager: Exception in ProcessTestRunAttachmentsAsync: " + e);
 
-                eventHandler?.HandleLogMessage(TestMessageLevel.Error, e.Message);
+                eventHandler?.HandleLogMessage(TestMessageLevel.Error, "TestRunAttachmentsProcessingManager: Exception in ProcessTestRunAttachmentsAsync: " + e);
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/TestRunAttachmentsProcessingManager.cs:95]: Moved back to `e.Message` and aligned the other exception too so we can avoid translation here, we have the logs above also in case of issue and the message of exception will be already translated.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/TestRunAttachmentsProcessingManager.cs [hunk 23]
```diff
@@ -91,52 +92,87 @@ private async Task<Collection<AttachmentSet>> InternalProcessTestRunAttachmentsA
...
+                                    attachments.Add(attachment);
+                                }
+                            }
                         }
                     }
                 }
+                catch (Exception e)
+                {
+                    EqtTrace.Error("TestRunAttachmentsProcessingManager: Exception in ProcessAttachmentsAsync: " + e);
+                    logger.SendMessage(TestMessageLevel.Error, "TestRunAttachmentsProcessingManager: Exception in ProcessAttachmentsAsync: " + e);
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/TestRunAttachmentsProcessingManager.cs:164]: moved to `e.Message`

File: src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelRunDataAggregator.cs [hunk 24]
```diff
@@ -157,6 +166,17 @@ public Exception GetAggregatedException()
                 if (exception != null) Exceptions.Add(exception);
                 if (executorUris != null) this.executorUris.AddRange(executorUris);
                 if (testRunStats != null) testRunStatsList.Add(testRunStats);
+
+                if (invokedDataCollectors != null && invokedDataCollectors.Count > 0)
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelRunDataAggregator.cs:170]: I took a deeper look, it's risky here, I prefer to keep as-is, if in future someone add code below and lose that return could miss his code if tests are not good(could return before the new code). But I'll improve with `invokedDataCollectors?.Count > 0`

File: src/Microsoft.TestPlatform.ObjectModel/PublicAPI/net/PublicAPI.Shipped.txt [hunk 25]
```diff
@@ -68,7 +68,7 @@ Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.IDataCollectionSi
...
-Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.IDataCollectorAttachmentProcessor.ProcessAttachmentSetsAsync(System.Collections.Generic.ICollection<Microsoft.VisualStudio.TestPlatform.ObjectModel.AttachmentSet> attachments, System.IProgress<int> progressReporter, Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging.IMessageLogger logger, System.Threading.CancellationToken cancellationToken) -> System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Microsoft.VisualStudio.TestPlatform.ObjectModel.AttachmentSet>>
+Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.IDataCollectorAttachmentProcessor.ProcessAttachmentSetsAsync(System.Xml.XmlElement configurationElement, System.Collections.Generic.ICollection<Microsoft.VisualStudio.TestPlatform.ObjectModel.AttachmentSet> attachments, System.IProgress<int> progressReporter, Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging.IMessageLogger logger, System.Threading.CancellationToken cancellationToken) -> System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Microsoft.VisualStudio.TestPlatform.ObjectModel.AttachmentSet>>
```
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.ObjectModel/PublicAPI/net/PublicAPI.Shipped.txt:71]: Discussed off-line, we'll break current api because is not used today by anyone.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 1 above)
Comment (AbhitejJohn) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs:30]: Would be nice if we could add that detail to the comment as well.

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 3 above)
Comment (AbhitejJohn) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs]: How is that different from test adapters though? Dont we refresh the cache based on the adapter version?

File: src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs (hunk 5 above)
Comment (AbhitejJohn) [reply src/Microsoft.TestPlatform.CrossPlatEngine/AttachmentsProcessing/DataCollectorAttachmentsProcessorsFactory.cs]: So the attachment processor would be coming in from the Code Coverage data collector nuget package eh?

File: src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs (hunk 7 above)
Comment (AbhitejJohn) [reply src/Microsoft.TestPlatform.ObjectModel/DataCollector/IConfigurableDataCollectorAttachmentProcessor.cs]: yeah, adding additional runsettings data would need to break the interface again, so I was hoping we could just do that once.

File: src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs (hunk 9 above)
Comment (AbhitejJohn) [reply src/Microsoft.TestPlatform.Common/Utilities/MetadataReaderHelper.cs:128]: Could we add that as a comment to code too please?

**Review by cvpoienaru — APPROVED** [review]

**Review by cvpoienaru — APPROVED** [review]

File: src/Microsoft.TestPlatform.CrossPlatEngine/PublicAPI/PublicAPI.Shipped.txt [hunk 26]
```diff
@@ -103,10 +103,6 @@ Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestHostManagerFactory
 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestHostManagerFactory.GetDiscoveryManager() -> Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.TesthostProtocol.IDiscoveryManager
 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestHostManagerFactory.GetExecutionManager() -> Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.TesthostProtocol.IExecutionManager
 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestHostManagerFactory.TestHostManagerFactory(Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.IRequestData requestData) -> void
-Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestRunAttachmentsProcessing.TestRunAttachmentsProcessingManager
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.CrossPlatEngine/PublicAPI/PublicAPI.Shipped.txt:106]: @jakubch1 I saw that this class implements an internal interface and it's an internal detail, I think we can move the implementation to internal too and remove from public surface

Comment (jakubch1) [reply src/Microsoft.TestPlatform.CrossPlatEngine/PublicAPI/PublicAPI.Shipped.txt:106]: sure, let's do it

File: src/Microsoft.TestPlatform.ObjectModel/PublicAPI/PublicAPI.Shipped.txt [hunk 27]
```diff
@@ -339,14 +343,15 @@ Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunChangedEventArgs.N
...
 Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunChangedEventArgs.TestRunStatistics.get -> Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunStatistics
 Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunCompleteEventArgs
+Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunCompleteEventArgs.TestRunCompleteEventArgs(Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunStatistics stats, bool isCanceled, bool isAborted, System.Exception error, System.Collections.ObjectModel.Collection<Microsoft.VisualStudio.TestPlatform.ObjectModel.AttachmentSet> attachmentSets, System.Collections.ObjectModel.Collection<Microsoft.VisualStudio.TestPlatform.ObjectModel.InvokedDataCollector> invokedDataCollectors, System.TimeSpan elapsedTime) -> void
```
Comment (nohwnd) [inline src/Microsoft.TestPlatform.ObjectModel/PublicAPI/PublicAPI.Shipped.txt:346]: This adds the invokedDataCollectors but does not keep the previous constructor, which is not a backwards compatible change in public API. Is there a good reason we should do it this way?

File: src/Microsoft.TestPlatform.Common/PublicAPI/PublicAPI.Shipped.txt [hunk 28]
```diff
@@ -20,9 +21,10 @@ Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException
 Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException.InvalidLoggerException(string message) -> void
 Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException.InvalidLoggerException(string message, System.Exception innerException) -> void
 Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.DataCollectorMetadata
-Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.DataCollectorMetadata.DataCollectorMetadata(string extension, string friendlyName) -> void
+Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.DataCollectorMetadata.DataCollectorMetadata(string extension, string friendlyName, bool hasAttachmentProcessor) -> void
```
Comment (nohwnd) [inline src/Microsoft.TestPlatform.Common/PublicAPI/PublicAPI.Shipped.txt:24]: This would break the exitsting public api. Is there a reason why this is okay?

Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/PublicAPI/PublicAPI.Shipped.txt:24]: DataCollectorMetadata is an internal type for the datacollector extensione...I don't expect external usage outside platform. I don't see usage around https://grep.app/search?q=DataCollectorMetadata&regexp=true http://index/?query=DataCollectorMetadata
The way the metadata object is created is by convention(Type, metadata) 

https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.Common/ExtensionFramework/Utilities/LazyExtension.cs#L161

I don't see back-compat issue here, but if you're concerned about it we can keep old ctor and set false there. That value is used to have better performance during attachment processor creation, if hasAttachmentProcessor is false we skip dll loading/inspection.

File: src/Microsoft.TestPlatform.ObjectModel/PublicAPI/PublicAPI.Shipped.txt (hunk 27 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.ObjectModel/PublicAPI/PublicAPI.Shipped.txt:346]: I did some test with old SDK and this event is created/used inside runner and serialized/deserialized with translator inside TE.
I see few usage inside UTs 
http://index/?query=TestRunCompleteEventArgs&rightProject=VS(Repo)&file=src%5Cvset%5CAgile%5CTestPlatform%5Csuitesrc%5CCore%5CTDD%5CLogging%5CTestRunCompleteEventArgsBehaviors.cs&rightSymbol=ltzdatsjdorb 
https://grep.app/search?q=TestRunCompleteEventArgs&regexp=true&filter[repo][0]=stryker-mutator/stryker-net

Do you see possible runtime issue?

Anyway as like the below one, I'll add overload, I liked the idea to start to narrow down the public api, but if you feel the risk here it's ok to me.

Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.ObjectModel/PublicAPI/PublicAPI.Shipped.txt:347]: Overload added

File: src/Microsoft.TestPlatform.Common/PublicAPI/PublicAPI.Shipped.txt (hunk 28 above)
Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.Common/PublicAPI/PublicAPI.Shipped.txt:26]: Overload added

**Review by nohwnd — APPROVED** [review]
