### PR TITLE
Handle correctly waiting for process exit on Unix systems

### LINKED ISSUE #3375: Process error and exit callbacks are received in incorrect order for Linux
Investigating the issue https://github.com/dotnet/sdk/issues/22311 lead me to discover that we are not handling properly wait for exit in our process helper for Linux. This is causing us to receive the exit callback before having flushed all output/error callbacks.

We are awaiting for some [guidance from runtime team](https://github.com/dotnet/runtime/issues/65377) before submitting the PR to fix it.

Thank you @ArturDorochowicz for reporting this issue!

### PR DESCRIPTION
**Pull request by Evangelink**
## Description
Handle correctly waiting for process exit on Unix systems.

## Related issue
Fixes #3375

### CODE REVIEW

File: test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs [hunk 1]
```diff
@@ -599,6 +599,11 @@ protected static void ExecuteApplication(string path, string args, out string st
             throw new ArgumentException("Executable path must not be null or whitespace.", nameof(path));
         }
 
+        if (!File.Exists(path))
```
Comment (Evangelink) [inline test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs:602]: Without this check we end up with error like `System.ComponentModel.Win32Exception: No such file or directory` which isn't really helpful.

File: test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+using System.IO;
+
+using Microsoft.TestPlatform.TestUtilities;
+using Microsoft.VisualStudio.TestTools.UnitTesting;
+
+namespace Microsoft.TestPlatform.AcceptanceTests;
+
+[TestClass]
+public class ProcessTests : AcceptanceTestBase
```
Comment (Evangelink) [inline test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs:12]: I couldn't really find in which existing type this would fit best so I created this one, feel free to suggest alternative.

File: src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs [hunk 3]
```diff
@@ -80,21 +82,38 @@ void InitializeAndStart()
...
+                            var cts = new CancellationTokenSource(500);
+#if NET5_0_OR_GREATER
+                            await p.WaitForExitAsync(cts.Token);
+#else
+                            await Task.Run(() => p.WaitForExit(), cts.Token);
+#endif
+                        }
+                        catch (Exception ex) when (ex is InvalidOperationException or TaskCanceledException)
+                        {
+                        }
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs:112]: can be useful a log here?

File: test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+    public void MissingFrameworkTextIsCorrectlyDisplayed(RunnerInfo runnerInfo)
+    {
+        // Arrange
+        SetTestEnvironment(_testEnvironment, runnerInfo);
+        using var tempDir = new TempDirectory();
+        var assemblyPath = GetAssetFullPath("SimpleTestProjectMessedUpTargetFramework.dll", Core21TargetFramework);
+        var runtimeConfigJson = Path.Combine(Path.GetDirectoryName(assemblyPath), "SimpleTestProjectMessedUpTargetFramework.runtimeconfig.json");
+        var fileContent = File.ReadAllText(runtimeConfigJson);
+        var updatedContent = fileContent.Replace("\"version\": \"2.1.0\"", "\"version\": \"42\"");
+        File.WriteAllText(runtimeConfigJson, updatedContent);
```
Comment (MarcoRossignoli) [inline test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs:25]: this test is modifying the assets right?

File: test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs (hunk 2 above)
Comment (MarcoRossignoli) [reply test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs:12]: `ProcessesInteractionTests`?

**Review by MarcoRossignoli — APPROVED** [review]

File: src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs (hunk 3 above)
Comment (Evangelink) [reply src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs:112]: Maybe yes. I will have two separate logs depending on the exception type.

File: test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs (hunk 4 above)
Comment (Evangelink) [reply test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs:25]: Yes that's why I created a new test asset. I originally thought that we were doing a local copy of the asset for each test but we don't so I wasn't sure how to best do this.

Given the question, I should probably put a comment in the code to explain what/why.

Thanks for pointing it out!

File: src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs (hunk 3 above)
Comment (Evangelink) [reply src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs:112]: Actually, I can't because this project references no other project (so no access to `EqtTrace`). The signature is public so I can't even take some extra parameter.

File: test/Microsoft.TestPlatform.AcceptanceTests/ProcessesInteractionTests.cs [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+        {
+            // On the contrary to other tests, we need to modify the test asset we are using to replace
+            // the target framework with an invalid framework. This is why we have a specific test asset
+            // that's only meant to be used by this project.
+            // Having an invalid framework is a way to reproduce an issue we had on Unix, where we were
+            // not handling correctly the process exit (causing us to not let time to the process to
+            // flush its output and error streams).See https://github.com/microsoft/vstest/issues/3375
+            var runtimeConfigJson = Path.Combine(Path.GetDirectoryName(assemblyPath), testAssetProjectName + ".runtimeconfig.json");
+            var fileContent = File.ReadAllText(runtimeConfigJson);
+            var updatedContent = fileContent.Replace("\"version\": \"2.1.0\"", "\"version\": \"42\"");
```
Comment (nohwnd) [inline test/Microsoft.TestPlatform.AcceptanceTests/ProcessesInteractionTests.cs:43]: maybe use some version that is lower than when is current, or that we know was not published, I think 2.8.0 was my original proposal? Or 0.0.0?

Comment (Evangelink) [reply test/Microsoft.TestPlatform.AcceptanceTests/ProcessesInteractionTests.cs]: I went with `0.0.0`, it seems easier to notice this is invalid version.

File: test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+using Microsoft.VisualStudio.TestTools.UnitTesting;
+
+namespace Microsoft.TestPlatform.AcceptanceTests;
+
+[TestClass]
+public class ProcessTests : AcceptanceTestBase
+{
+    [TestMethod]
+    [NetCoreTargetFrameworkDataSource]
+    public void MissingFrameworkTextIsCorrectlyDisplayed(RunnerInfo runnerInfo)
```
Comment (nohwnd) [inline test/Microsoft.TestPlatform.AcceptanceTests/ProcessTests.cs]:
```suggestion
    public void WhenTestHostProcessExitsBecauseTheTargetedRuntimeIsNoFoundThenTheMessageIsCapturedFromTheErrorOutput(RunnerInfo runnerInfo)
```

Might be also worth adding some more info about the problem we were solving.

**Review by nohwnd — APPROVED** [review]
