### PR TITLE
Use jsonSerializer2 for protocol version 3

### LINKED ISSUE #2623: Microsoft.NET.Test.Sdk v16.7.0 and later are ~4x slower than v16.6.1
## Description

Microsoft.NET.Test.Sdk v16.7.0 and later are ~4x slower than v16.6.1

I reported https://github.com/microsoft/vstest/issues/2215 a year ago, maybe these issues are related. That issue was fixed and I closed it.

What changed between 16.6.1 and 16.7.0? Serializing more data? Used new serializer version/nuget? Or something else?

## Steps to reproduce

.NET: 5.0.100

ClassLibrary1.csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- 16.6.1 or 16.9.0-preview-20201020-06 -->
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.0-preview-20201020-06" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="All" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.console" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
  </ItemGroup>

</Project>
```

Class1.cs:

```C#
using System.Collections.Generic;
using Xunit;

namespace ClassLibrary1
{
    public class Class1
    {
        [Theory]
        [MemberData(nameof(TestData))]
#pragma warning disable xUnit1026 // Theory methods should use all of their parameters
        public void Test1(int value)
#pragma warning restore xUnit1026 // Theory methods should use all of their parameters
        {
        }
        public static IEnumerable<object[]> TestData {
            get {
                for (int i = 0; i < 100_000; i++)
                    yield return new object[] { i };
            }
        }
    }
}
```

repro:

- Run the commands below
- Change the `Microsoft.NET.Test.Sdk` version: 16.6.1 <--> 16.9.0-preview-20201020-06
- Run the commands below again

```pwsh
dotnet build -v:m -c Release ClassLibrary1.csproj
Measure-Command { dotnet test -c Release -f net5.0 --no-build ClassLibrary1.csproj | Out-Default }
```

Version | Time | Verdict
-------|----------|--------
16.6.1 | 18.9 seconds | ✔️
16.9.0-preview-20201020-06 | 65.7 seconds | ❌

## Environment

Windows 10 20H2

Ubuntu 20.04 (WSL2)

### PR DESCRIPTION
**Pull request by nohwnd**
## Description
Updating the protocol to version 3 resulted in using serializer for v1, which sends two to three times more data. We cannot easily update how vstest.console behaves (e. g. the one shipped with net sdd 3.1.402), which will ask for protocol 3. So this PR will downgrade protocol 3 to 2. Any newer version would still be negotiable. Such as the protocol version 4 this PR introduces. Similarly protocol 3 is still using the old serializer, to keep compatibility in situations where we actually negotiate protocol 3. E.g. new console asking Test.SDK 16.7.1 for protocol version, where console would offer 4, but testhost would return 3. So 3 would be used with that specific version of SDK.

## Related issue
Fix #2623

### CODE REVIEW

File: src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs [hunk 1]
```diff
@@ -210,7 +211,22 @@ private T Deserialize<T>(JsonSerializer serializer, JToken jToken)
 
         private JsonSerializer GetPayloadSerializer(int? version)
         {
-            return version == 2 ? payloadSerializer2 : payloadSerializer;
+            if (version == null)
+            {
+                version = 1;
```
Comment (Sanan07) [inline src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs:216]: Why do you make version = 1, if it is null, why not 2?

File: test/Microsoft.TestPlatform.CommunicationUtilities.UnitTests/Serialization/TestResultSerializationTests.cs [hunk 2]
```diff
@@ -212,45 +216,66 @@ public void TestResultObjectShouldContainAllPropertiesOnDeserializationV2()
...
 
             this.VerifyDummyPropertyIsRegistered();
         }
 
         #endregion
 
+        #region future
+
+        [TestMethod]
+        public void TestResultSerializationShouldThrowWhenAVersionOfProtocolThatDoesNotExistYetIsProvided()
```
Comment (Sanan07) [inline test/Microsoft.TestPlatform.CommunicationUtilities.UnitTests/Serialization/TestResultSerializationTests.cs:267]: Could simplified to
`TestResultSerializationShouldThrowWhenProvidedProtocolVersionDoesNotExist`

**Review by Haplois — APPROVED** [review]

File: src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs (hunk 1 above)
Comment (nohwnd) [reply src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs:216]: Because 1 is the baseline at which all versions of test.sdk can communicate, 2 is optimization. So we ask over version 1: 

Console: Hey testhost, what is the highest version of protocol you can use? I can do 3.
Testhost: I can do 1. 
Console: Okay we will use 1. 

Or:

Console: Hey testhost, what is the highest version of protocol you can use? I can do 2.
Testhost: I can do 4. 
Console: Okay we will use 2.

File: test/Microsoft.TestPlatform.CommunicationUtilities.UnitTests/Serialization/TestResultSerializationTests.cs (hunk 2 above)
Comment (nohwnd) [reply test/Microsoft.TestPlatform.CommunicationUtilities.UnitTests/Serialization/TestResultSerializationTests.cs:267]: Thx. Consider making it a suggestion next time :)

image

File: src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs [hunk 3]
```diff
@@ -210,7 +211,24 @@ private T Deserialize<T>(JsonSerializer serializer, JToken jToken)
...
+            {
+                // 0 is used during negotiation
+                case 0:
+                case 1:
+                    return payloadSerializer;
+                case 2:
+                case 3:
+                    return payloadSerializer2;
+                default:
+                    throw new NotSupportedException($"Protocol version {version} is not supported. " +
```
Comment (cvpoienaru) [inline src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs:229]: Should we localize the exception message ?

**Review by cvpoienaru — APPROVED** [review]

File: src/Microsoft.TestPlatform.CrossPlatEngine/EventHandlers/TestRequestHandler.cs [hunk 4]
```diff
@@ -261,7 +263,36 @@ public void OnMessageReceived(object sender, MessageReceivedEventArgs messageRec
...
+                    // would be negotiated.
+                    if (negotiatedVersion != 3)
+                    {
+                        this.protocolVersion = negotiatedVersion;
+                    }
+                    else
+                    {
+                        var flag = Environment.GetEnvironmentVariable("VSTEST_DISABLE_PROTOCOL_3_VERSION_DOWNGRADE");
+                        var flagIsEnabled = flag != null && flag != "0";
+                        var dowgradeIsDisabled = flagIsEnabled;
```
[the remark this answers is not in the document]
Comment (nohwnd) [reply src/Microsoft.TestPlatform.CrossPlatEngine/EventHandlers/TestRequestHandler.cs:286]: No technical reason, it's just easier to understand the rule without doing two negations in my head.

File: src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs (hunk 3 above)
Comment (nohwnd) [reply src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs:234]: Imho not necessary.

File: src/Microsoft.TestPlatform.CrossPlatEngine/EventHandlers/TestRequestHandler.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (nohwnd) [reply src/Microsoft.TestPlatform.CrossPlatEngine/EventHandlers/TestRequestHandler.cs:286]: Fixed typo.

File: test/TranslationLayer.UnitTests/VsTestConsoleRequestSenderTests.cs [hunk 5]
```diff
@@ -37,7 +37,7 @@ public class VsTestConsoleRequestSenderTests
 
         private readonly int WaitTimeout = 2000;
 
-        private int protocolVersion = 3;
+        private int protocolVersion = 4;
```
Comment (fhnaseer) [inline test/TranslationLayer.UnitTests/VsTestConsoleRequestSenderTests.cs:40]: `const` for all version numbers?,
