### PR TITLE
Fix DOTNET_ROOT env var for .NET 6.0+

### LINKED ISSUE #3586: Stop setting DOTNET_ROOT in `dotnet test`
## Steps to reproduce
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

Further information can be found in https://github.com/dotnet/runtime/issues/68180.

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes [AB#1528950](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1528950) and fixes #3586

### CODE REVIEW

File: test/Microsoft.TestPlatform.TestHostProvider.UnitTests/Hosting/DotnetTestHostManagerTests.cs [hunk 1]
```diff
@@ -987,6 +987,104 @@ public async Task CleanTestHostAsyncShouldNotThrowIfTestHostIsNotStarted()
...
+        // Act
+        _dotnetHostManager.ForwardDotnetRootEnvironmentVariable(startInfo);
+
+        // Assert
+        Assert.AreEqual(0, startInfo.EnvironmentVariables.Count);
+    }
+
+    [TestMethod]
+    [DataRow("VSTEST_WINAPPHOST_DOTNET_ROOT(x86)", PlatformArchitecture.X86)]
+    [DataRow("VSTEST_WINAPPHOST_DOTNET_ROOT(x86)", PlatformArchitecture.X64)]
```
Comment (Evangelink) [inline test/Microsoft.TestPlatform.TestHostProvider.UnitTests/Hosting/DotnetTestHostManagerTests.cs:1056]: I am currently not checking if the platform matching makes sense or not and simply forward the first found variable.

File: test/Microsoft.TestPlatform.TestHostProvider.UnitTests/Hosting/DotnetTestHostManagerTests.cs [hunk 2]
```diff
@@ -987,6 +987,104 @@ public async Task CleanTestHostAsyncShouldNotThrowIfTestHostIsNotStarted()
...
+
+    [TestMethod]
+    [DataRow("DOTNET_ROOT(x86)", "net5.0")]
+    [DataRow("DOTNET_ROOT(x86)", "net6.0")]
+    [DataRow("DOTNET_ROOT", "net5.0")]
+    [DataRow("DOTNET_ROOT", "net6.0")]
+    [DataRow("DOTNET_ROOT_X86", "net5.0")]
+    [DataRow("DOTNET_ROOT_X86", "net6.0")]
+    [DataRow("DOTNET_ROOT_X64", "net5.0")]
+    [DataRow("DOTNET_ROOT_X64", "net6.0")]
```
Comment (MarcoRossignoli) [inline test/Microsoft.TestPlatform.TestHostProvider.UnitTests/Hosting/DotnetTestHostManagerTests.cs:1029]: maybe add something with ARM64

File: src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs [hunk 3]
```diff
@@ -565,6 +550,33 @@ bool SilentlyForceToX64()
         }
     }
 
+    internal /* for testing purposes */ void ForwardDotnetRootEnvironmentVariable(TestProcessStartInfo startInfo)
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:553]: cc: @vitek-karas

File: src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs [hunk 4]
```diff
@@ -565,6 +550,33 @@ bool SilentlyForceToX64()
...
+            vstestDotnetRootEnvValue = _environmentVariableHelper.GetEnvironmentVariable(vstestDotnetRootEnvName);
+
+            if (vstestDotnetRootEnvValue is null)
+            {
+                EqtTrace.Verbose($"DotnetTestHostmanager.LaunchTestHostAsync: Prefix '{prefix}*' not found in env variables");
+                return;
+            }
+        }
+
+        string dotnetRootEnvName = Version.Parse(_targetFramework.Version) >= Version6_0
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:572]: can you add a comment with the ref to the `dotnet run` inside SDK?

File: src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs [hunk 5]
```diff
@@ -565,6 +550,33 @@ bool SilentlyForceToX64()
...
+            ? $"{dotnetRoot}_{_processHelper.GetCurrentProcessArchitecture().ToString().ToUpperInvariant()}"
```
Comment (vitek-karas) [inline src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:573]: @MarcoRossignoli can you please remind me what does the "caller" do in this case? Is the `VSTEST_WINAPPHOST_..` set for .NET 6+ or not?

If it's set I find it weird that we intentionally ignore it here.

Comment (Evangelink) [reply src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:573]: Yes you are right @vitek-karas , I will add a check to ensure the variable is not set by user before this forward.

Thank you for the review!

Comment (MarcoRossignoli) [reply src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:573]: It's always set inside the SDK we don't know yet the tfm.

File: test/TestAssets/Net6Launches32BitsProcess/Test32Bit.cs [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+
+        Assert.IsTrue(string.IsNullOrEmpty(stderr),
+            $"There was some error in process run: {stderr}");
+        Assert.IsTrue(string.IsNullOrEmpty(Environment.GetEnvironmentVariable("DOTNET_ROOT")),
+            "Env var DOTNET_ROOT was found.");
+        Assert.IsTrue(string.IsNullOrEmpty(Environment.GetEnvironmentVariable("DOTNET_ROOT(x86)")),
+            "Env var DOTNET_ROOT(x86) was found.");
+        Assert.IsTrue(string.IsNullOrEmpty(Environment.GetEnvironmentVariable("DOTNET_ROOT_X86")),
+            "Env var DOTNET_ROOT_X86 was found.");
+        Assert.IsFalse(string.IsNullOrEmpty(Environment.GetEnvironmentVariable("DOTNET_ROOT_X64")),
```
Comment (MarcoRossignoli) [inline test/TestAssets/Net6Launches32BitsProcess/Test32Bit.cs:41]: can we test <6 cases?

File: test/TestAssets/TestProcess32/Program.cs [hunk 7]
```diff
@@ -0,0 +1,4 @@
+﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT license. See LICENSE file in the project root for full license information.
+
+Console.WriteLine($"Am I 32bit?: {!Environment.Is64BitProcess}");
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply test/TestAssets/TestProcess32/Program.cs:5]: @MarcoRossignoli I haven't added any check here as I am now forcing the environment variable from calling point so it seemed to be adding no value. Let me know if you think we should still make some checks here.

File: test/Microsoft.TestPlatform.AcceptanceTests/DotnetArchitectureTests.cs [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+    public static IEnumerable<object[]> GetRunnerAndDotnetRootEnvVar()
+    {
+        var runnerDataSource = new NetCoreTargetFrameworkDataSource(useDesktopRunner: false);
+        foreach (var entry in runnerDataSource.GetData(null))
+        {
+            yield return new object[] { entry[0], "net6.0", "6.0.100", "DOTNET_ROOT_X86" };
+            yield return new object[] { entry[0], "net6.0", "6.0.100", "DOTNET_ROOT(x86)" };
+            yield return new object[] { entry[0], "net6.0", "6.0.100", "DOTNET_ROOT" };
+
+            yield return new object[] { entry[0], "net5.0", "5.0.100", "DOTNET_ROOT_X86" };
```
Comment (Evangelink) [inline test/Microsoft.TestPlatform.AcceptanceTests/DotnetArchitectureTests.cs:25]: I am still not 100% sure why this case works locally, I would expect it to fail because that's not understood by . NET 5 and I am correctly pinning SDK version with global.json.

File: src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs [hunk 9]
```diff
@@ -565,6 +550,53 @@ bool SilentlyForceToX64()
...
+        string dotnetRootEnvName;
+        if (Version.Parse(_targetFramework.Version) >= Version6_0)
+        {
+            dotnetRootEnvName = $"{dotnetRoot}_{_processHelper.GetCurrentProcessArchitecture().ToString().ToUpperInvariant()}";
+
+            // SDK side of TP is not checking for the .NET6.0+ environment variables so we want to make sure we
+            // are not overriding user definition.
+            if (_environmentVariableHelper.GetEnvironmentVariable(dotnetRootEnvName) is not null)
+            {
+                EqtTrace.Verbose($"DotnetTestHostmanager.LaunchTestHostAsync: Found '{vstestDotnetRootEnvName}' in env variables but also found '{dotnetRootEnvName}'. Skipping forwarding.");
```
Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:587]: can you print the value inside the log?

Comment (MarcoRossignoli) [inline src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:587]: can you print the value inside the log?

File: test/TestAssets/TestProcess32/Program.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (MarcoRossignoli) [reply test/TestAssets/TestProcess32/Program.cs:5]: I would add the same...it's true that we're forcing...but it could work also for "fallback" reason...if for some reason we'll update the test. We should check that we're resolving correctly checking env var and the location of `typeof(object).Assembly.Location` directory

**Review by MarcoRossignoli — APPROVED** [review]

**Comment by MarcoRossignoli** [comment]
Some more info https://github.com/dotnet/runtime/issues/68180#issuecomment-1102402697
