### PR TITLE
Fix string conversion of `Microsoft.TestPlatform.Extensions.TrxLogger.ObjectMode.TestOutcome`

### LINKED ISSUE #4227: TRX writer emits `Min` as outcome instead of `Error` in .NET 7.0
## Description

When using `dotnet test -l trx` in .NET 7.0, the TRX file writes an unexpected enum value (due to an undocumented change in .NET 7.0's `Enum.ToString()`).

## Steps to reproduce

See above

## Expected behavior

```xml
<RunInfo outcome="Error" ...
```

## Actual behavior

```xml
<RunInfo outcome="Min" ...
```

## Environment

```
> dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
By design we cannot have a "correct" value from a string conversion from enum for the same underlying value.
The behavior changed since 7.0 and now the runtime is returning `Min` and not `Error`

fixed https://github.com/microsoft/vstest/issues/4227

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
```cs
using System.ComponentModel;


TestOutcome value = TestOutcome.Error;
Type valueType = value.GetType();
TypeConverter convert = TypeDescriptor.GetConverter(valueType);
var valueToSave = convert.ConvertToInvariantString(value);
Console.WriteLine(valueToSave);

internal enum TestOutcome
{
    /// <summary>
    /// There was a system error while we were trying to execute a test.
    /// </summary>
    Error,

    /// <summary>
    /// Test was executed, but there were issues.
    /// Issues may involve exceptions or failed assertions.
    /// </summary>
    Failed,

    /// <summary>
    /// The test timed out
    /// </summary>
    Timeout,

    /// <summary>
    /// Test was aborted.
    /// This was not caused by a user gesture, but rather by a framework decision.
    /// </summary>
    Aborted,

    /// <summary>
    /// Test has completed, but we can't say if it passed or failed.
    /// May be used for aborted tests...
    /// </summary>
    Inconclusive,

    /// <summary>
    /// Test was executed w/o any issues, but run was aborted.
    /// </summary>
    PassedButRunAborted,

    /// <summary>
    /// Test had it chance for been executed but was not, as ITestElement.IsRunnable == false.
    /// </summary>
    NotRunnable,

    /// <summary>
    /// Test was not executed.
    /// This was caused by a user gesture - e.g. user hit stop button.
    /// </summary>
    NotExecuted,

    /// <summary>
    /// Test run was disconnected before it finished running.
    /// </summary>
    Disconnected,

    /// <summary>
    /// To be used by Run level results.
    /// This is not a failure.
    /// </summary>
    Warning,

    /// <summary>
    /// Test was executed w/o any issues.
    /// </summary>
    Passed,

    /// <summary>
    /// Test has completed, but there is no qualitative measure of completeness.
    /// </summary>
    Completed,

    /// <summary>
    /// Test is currently executing.
    /// </summary>
    InProgress,

    /// <summary>
    /// Test is in the execution queue, was not started yet.
    /// </summary>
    Pending,

    /// <summary>
    /// The min value of this enum
    /// </summary>
    Min = Error,

    /// <summary>
    /// The max value of this enum
    /// </summary>
    Max = Pending
}
```
net6.0 output `Error`
net7.0 output  `Min`

File: src/Microsoft.TestPlatform.Extensions.TrxLogger/ObjectModel/TestOutcome.cs [hunk 1]
```diff
@@ -88,13 +88,20 @@ internal enum TestOutcome
     /// </summary>
     Pending,
 
+    // NOTE: OLD CODE WAS  Min = Error and Max = Pending
+    // This doesn't work well with the coversion to string for the reason explained here:
+    // https://learn.microsoft.com/en-us/dotnet/api/system.enum.tostring?view=net-7.0
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.Extensions.TrxLogger/ObjectModel/TestOutcome.cs:93]: It's better not to force culture in URL

```suggestion
    // https://learn.microsoft.com/dotnet/api/system.enum.tostring?view=net-7.0
```

File: src/Microsoft.TestPlatform.Extensions.TrxLogger/ObjectModel/TestOutcome.cs [hunk 2]
```diff
@@ -88,13 +88,20 @@ internal enum TestOutcome
...
+    // Notes to Callers: If multiple enumeration members have the same underlying value and you attempt to retrieve the
+    // string representation of an enumeration member's name based on its underlying value
+    // We fixed removing the equality above to break less as possible. But the returned value won't be the expected Min/Max
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.Extensions.TrxLogger/ObjectModel/TestOutcome.cs:96]: Probably better as xml doc to have it discoverable for "users".

**Review by Evangelink — COMMENTED** [review]
I am assuming this isn't tested as we didn't get any failure. Could we add a test?

**Comment by MarcoRossignoli** [comment]
We found out that the enum is internal and we have only 1 friend, the unit test project, should be safe remove.

**Review by Evangelink — APPROVED** [review]
