### PR TITLE
Fix divide by zero in HTML logger

### LINKED ISSUE #2615: DivideByZeroException when there are no tests discovered
The verbose log contains following exception when there are no tests discovered (probably accidentally)

```
TpTrace Error: 0 : 70249, 5, 2020/11/03, 14:16:15.282, 1591260085400598, vstest.console.dll, InternalTestLoggerEvents.SendTestRunComplete: Exception occurred while calling handler of type Microsoft.VisualStudio.TestPlatform.Extensions.HtmlLogger.HtmlLogger for TestRunCompleteEventArgs: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.VisualStudio.TestPlatform.Extensions.HtmlLogger.HtmlLogger.TestRunCompleteHandler(Object sender, TestRunCompleteEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(Delegate delegates, Object sender, EventArgs args, String traceDisplayName)
```

this points to this line https://github.com/microsoft/vstest/blob/aabbb714e344c0edd2482d6c3b7c2b3963594ad3/src/Microsoft.TestPlatform.Extensions.HtmlLogger/HtmlLogger.cs#L285

AB#1272732

### PR DESCRIPTION
**Pull request by nohwnd**
## Description
Fix division by zero when there are no tests discovered.

## Related issue
Fix #2615
Fix AB#1272732

### CODE REVIEW

File: src/Microsoft.TestPlatform.Extensions.HtmlLogger/HtmlLogger.cs [hunk 1]
```diff
@@ -282,7 +282,7 @@ public void TestRunCompleteHandler(object sender, TestRunCompleteEventArgs e)
                 PassedTests = PassedTests,
                 TotalTests = TotalTests,
                 SkippedTests = SkippedTests,
-                PassPercentage = (PassedTests * 100) / TotalTests,
+                PassPercentage = (PassedTests * 100) / (TotalTests >= 1 ? TotalTests : 1),
```
Comment (Sanan07) [inline src/Microsoft.TestPlatform.Extensions.HtmlLogger/HtmlLogger.cs:285]: Would be better to add some comment explaining DivideByZero case, cause it is not obvious why we change TotalTests  = 1. Or change the implementation to make PassPercentage = 0 when TotalTests  = 0.

Comment (nohwnd) [reply src/Microsoft.TestPlatform.Extensions.HtmlLogger/HtmlLogger.cs:285]: Good point, I think I had it done the second way before, but lost the commit somewhere. Will change to return 0 when total tests is 0.

**Review by Haplois — APPROVED** [review]

File: src/Microsoft.TestPlatform.Extensions.HtmlLogger/HtmlLogger.cs [hunk 2]
```diff
@@ -282,7 +282,7 @@ public void TestRunCompleteHandler(object sender, TestRunCompleteEventArgs e)
                 PassedTests = PassedTests,
                 TotalTests = TotalTests,
                 SkippedTests = SkippedTests,
-                PassPercentage = (PassedTests * 100) / TotalTests,
+                PassPercentage = TotalTests != 0 ? PassedTests * 100 / TotalTests : 0,
```
Comment (Sanan07) [inline src/Microsoft.TestPlatform.Extensions.HtmlLogger/HtmlLogger.cs:285]:
```suggestion
                PassPercentage = TotalTests == 0 ? 0 : PassedTests * 100 / TotalTests
```

**Review by Sanan07 — APPROVED** [review]

**Review by Haplois — APPROVED** [review]
