### PR TITLE
1187 add support for xplat vstest console in translationlayer

### LINKED ISSUE #1887: VsTestConsoleWrapper does not support vstest.console.dll
## Description
We are building a mutation testing framework for dotnet framework and dotnet core. We are trying to integrate vstest using the Microsoft.TestPlatform.TranslationLayer and Microsoft.TestPlatform.Portable nuget packages. This works on windows by providing the vstest.console.exe path from the nuget package to VsTestConsoleWrapper which provides the path to the [VsTestConsoleProcessManager](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs#L77), however this does not seem to work for vstest.console.dll because the wrapper does not detect that the dll should be run using using dotnet with vstest.console.dll as the argument instead of trying to start a process for the dll directly. The IntegrationTestBase in the [Microsoft.TestPlatform.TestUtilities](https://github.com/Microsoft/vstest/blob/master/test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs#L372) project contains logic to differentiate between starting a vstest.console.exe process and starting a dotnet vstest.console.dll  process. We need this logic in the TranslationLayer to be able to add vstest integration in our mutation test framework.

## Steps to reproduce
 1. Create a dotnet console app using packages Microsoft.TestPlatform, Microsoft.TestPlatform.Portable and Microsoft.TestPlatform.TranslationLayer.
 1. Provide vstest.console.dll from Portable package, and a logfile location to VsTestConsoleWrapper
 1. Call StartSession
 1. Call InitializeExtensions with TestAdapters from Extensions folder in Portable package
 1. Call DiscoverTests on a test project

I also have a proof of concept of our vstest integration on this branch here: https://github.com/stryker-mutator/stryker-net/tree/183-vstest-integration/src/Stryker.Core/Stryker.Core/TestRunners/vstest

## Expected behavior
vstest.console.dll starts up, discovers tests in test project and returns discovered tests to TranslationLayer. Logging is available to see what vstest.console.dll executed.

## Actual behavior
vstest.console.dll tries to start up, immediately fails because OS does not know how to run a dll, no logging is available because vstest.console.dll never actually started

## Diagnostic logs
No logs are available because vstest.console.dll never actually started.

## Environment
OS: Windows 10 Enterprise
Packages and versions:
 - Dotnet Core 2.1.0
 - Microsoft.TestPlatform: 16.0.0-preview-20181205-02
 - Microsoft.TestPlatform.Portable: 16.0.0-preview-20181205-02
 - Microsoft.TestPlatform.TranslationLayer: 16.0.0-preview-20181205-02

### PR DESCRIPTION
**Pull request by rouke-broersma**
## Description
With this PR it will be possible to use the translationlayer with vstest.console.dll instead of only with vstest.console.exe. I have also removed all test logic from the unit tests that determined vstest.console.dll was not supported. I have successfully used the translationlayer dll resulting from this change to start unit tests against a dotnet core project using vstest.console.dll from the portable nuget package.

However, I have not been able to get all unit tests working yet. The vstest.console.dll used in the acceptance tests seems to be invalid (compared to the one in the portable nuget package). I get this error message:

```
PS U:\> dotnet C:\git\vstest\src\package\package\bin\Debug\netcoreapp2.0\vstest.console.dll /parentprocessid:28400 /port
:63362 /diag:"C:\Users\roukeb\AppData\Local\Temp\VSTestConsoleWrapperLogs\tmp1C9F.tmp";tracelevel=Verbose
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\git\vstest\src\package\package\bin\Debug\netcoreapp2.0\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\git\vstest\src\package\package\bin\Debug\netcoreapp2.0\vstest.console.runtimeconfig.json file specifying the appropriate framework.
tracelevel=Verbose : The term 'tracelevel=Verbose' is not recognized as the name of a cmdlet, function, script file, or
 operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try a
gain.
At line:1 char:200
+ ... a\Local\Temp\VSTestConsoleWrapperLogs\tmp1C9F.tmp";tracelevel=Verbose
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (tracelevel=Verbose:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I would appreciate assistance with fixing this before this PR can be merged.
## Related issue
Fixes #1887

### CODE REVIEW

File: src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs [hunk 1]
```diff
@@ -109,8 +118,10 @@ public void ShutdownProcess()
             // Ideally process should die by itself
             if (IsProcessInitialized())
             {
-                this.process.Kill();
-                this.process.Dispose();
+                vstestConsoleExited = true;
```
Comment (mayankbansal018) [inline src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs]: can you also ensure process is Killed

File: src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs [hunk 2]
```diff
@@ -119,26 +130,54 @@ private void Process_Exited(object sender, EventArgs e)
...
+            {
+                args.Insert(0, vstestConsolePath);
+            }
+
             return args.ToArray();
         }
+
+        private string GetConsoleRunner()
+        {
+            return isNetCoreRunner ? DOTNET_EXECUTABLE : vstestConsolePath;
```
Comment (mayankbansal018) [inline src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs]: >DOTNET_EXECUTABLE [](start = 37, length = 17)

The way we find path for dotnet.exe on different platforms is shared at [https://github.com/Microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.CoreUtilities/Helpers/DotnetHostHelper.cs#L43](https://github.com/Microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.CoreUtilities/Helpers/DotnetHostHelper.cs#L43)

Here it seems you are assuming that dotnet is installed on machine, & is added to path variables. Can you please handle scenarios where it might not be the case

**Comment by mayankbansal018** [comment]
A bunch of tests are failing because the number of processes(dotnet) being spawned is changing, can you please give me access to your branch. I'll help you fix these tests.

File: src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs (hunk 1 above)
Comment (Mobrockers) [reply src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs]: I missed that one, fixed

**Comment by Mobrockers** [comment]
> A bunch of tests are failing because the number of processes(dotnet) being spawned is changing, can you please give me access to your branch. I'll help you fix these tests.

I believe I created this PR with change permissions for reviewers enabled, so you should have access to my branch.

**Comment by singhsarab** [comment]
>         /// <summary>

Fix the docs as well.

---
Refers to: test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs:365 in cda8bf9. [](commit_id = cda8bf9705b3c23ba151548d16a04587ac62e653, deletion_comment = False)

File: test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs [hunk 3]
```diff
@@ -379,7 +378,8 @@ public virtual string GetConsoleRunnerPath()
             }
```
Comment (singhsarab) [inline test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs]: Variable name are bit confusing.
When will this isVsTestConsoleDLLScenario be different from IsNetCoreRunner() ?

Doubt arising because RunTestsWithFilterTests invokes GetConsoleRunnerPath( IsNetCoreRunner())

File: test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs [hunk 4]
```diff
@@ -419,7 +419,7 @@ public IVsTestConsoleWrapper GetVsTestConsoleWrapper()
 
             Console.WriteLine($"Logging diagnostics in {logFilePath}");
 
-            var vstestConsoleWrapper = new VsTestConsoleWrapper(this.GetConsoleRunnerPath(), new ConsoleParameters(){LogFilePath = logFilePath});
+            var vstestConsoleWrapper = new VsTestConsoleWrapper(this.GetConsoleRunnerPath(isVsTestConsoleDLLScenario), Path.Combine(this.testEnvironment.ToolsDirectory, @"dotnet\dotnet.exe"), new ConsoleParameters() { LogFilePath = logFilePath });
```
Comment (singhsarab) [inline test/Microsoft.TestPlatform.TestUtilities/IntegrationTestBase.cs]: >GetConsoleRunnerPath [](start = 69, length = 20)

Instead of using GetConsoleRunnerPath, have another api.

File: src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs [hunk 5]
```diff
@@ -4,14 +4,15 @@
...
+    using Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers;
     using Microsoft.VisualStudio.TestPlatform.ObjectModel;
     using System;
     using System.Collections.Generic;
     using System.Diagnostics;
     using System.Globalization;
 
     /// <summary>
-    /// Vstest.console.exe process manager
+    /// Vstest.console process manager
```
Comment (singhsarab) [inline src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs]: Would have loved to see some unit tests for this class.

File: src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs [hunk 6]
```diff
@@ -72,33 +81,36 @@ public bool IsProcessInitialized()
...
+            {
+                UseShellExecute = false,
+                CreateNoWindow = true,
+                RedirectStandardOutput = true,
+                RedirectStandardError = true
+            };
 
-            EqtTrace.Verbose("VsTestCommandLineWrapper: {0} {1}", process.StartInfo.FileName,
-                process.StartInfo.Arguments);
+            EqtTrace.Verbose("VsTestCommandLineWrapper: {0} {1}", info.FileName, info.Arguments);
```
Comment (singhsarab) [inline src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs]: >VsTestCommandLineWrapper [](start = 30, length = 24)

Let's fix the logging to "VsTestConsoleProcessManager : Process Start Info : {0} {1}"

**Review by mayankbansal018 — APPROVED** [review]

**Comment by Mobrockers** [comment]
Is there anything more I should do for this PR to be merged?

**Comment by mayankbansal018** [comment]
@Mobrockers , I'll push the PR, once my colleague has gone through.

**Comment by Mobrockers** [comment]
@mayankbansal018 I am seeing some weird results using a nuget package created from this branch. vstest.console.dll fails to start (I see the dotnet.exe process for vstest.console.dll start up then immediately shut down) when connecting from the nuget package (uploaded to my own myget feed). When I was testing using the dll's itself referenced in my test project it worked as expected. 

I have the packages Microsoft.TestPlatform.TranslationLayer and Microsoft.TestPlatform.ObjectModel which contain the changes from this branch uploaded here: https://www.myget.org/feed/Packages/stryker-mutator-integrationtest

They do not work in my POC. When the dll's on my local system are referenced as assemblies through visual studio it does work. Any idea why?

**Comment by mayankbansal018** [comment]
@Mobrockers can you make sure you have dotnet core 2.0 installed when you are trying? Also I could be access that feed.

**Comment by Mobrockers** [comment]
@mayankbansal018 I have dotnet core 2.0 installed. I believe you should be able to access that feed, as it is public. 
The v3 feed url is: https://www.myget.org/F/stryker-mutator-integrationtest/api/v3/index.json
The v2 feed url is: https://www.myget.org/F/stryker-mutator-integrationtest/api/v2

**Comment by Mobrockers** [comment]
Checkout: https://github.com/stryker-mutator/stryker-net/tree/183-vstest-integration
Open: https://github.com/stryker-mutator/stryker-net/blob/183-vstest-integration/src/Stryker.CLI/Stryker.CLI.sln
Restore project using: https://www.myget.org/F/stryker-mutator-integrationtest/api/v3/index.json (this contains the nuget package from this pull request)
Add this launchSettings.json in visual studio:
```
{
  "profiles": {
    "vstest": {
      "commandName": "Project",
      "commandLineArgs": "-p \"ExampleProject.csproj\" -r \"['All']\" -f -tr vstest",
      "workingDirectory": "<REPO_LOCATION>stryker-net\\integrationtests\\IntegrationTests\\ExampleProject.XUnit"
    }
  }
}
```

Now if you start a debug run, my project should start using vstest.console.dll and it will not work.

If I then do the following, it does work for me
Checkout: https://github.com/Mobrockers/vstest/tree/1187_add_support_for_xpat_vstest_console_in_translationlayer
Build vstest from above branch^
Remove nuget references from Stryker.Core.csproj:
```
<PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="16.0.0-dev" />
<PackageReference Include="Microsoft.TestPlatform.TranslationLayer" Version="16.0.0-dev" />
```

Add assembly references to Microsoft.TestPlatform.ObjectModel.dll and Microsoft.TestPlatform.TranslationLayer.dll built locally from this PR.

Now it vstest.console.dll successfully starts up and runs tests on my machine.

**Comment by mayankbansal018** [comment]
@Mobrockers can you please drop a mail to maban at microsoft dot com. I'll set up a meeting with you to diagnose this issue.
Please do let me know what time zone you work in, & what will be your preferred work timings. I work in India Time Zone

**Comment by Mobrockers** [comment]
@mayankbansal018 Is it possible to give an indication of when a new (preview) nuget package can be release with these changes?

**Comment by mayankbansal018** [comment]
@Mobrockers we recently release a package last week itself, so most likely our next release will be 2 weeks from now.

**Comment by Mobrockers** [comment]
@mayankbansal018 Thank you for your help :)
