### PR TITLE
Fixed bugs in ManagedMethod parsing, and updated hierarchies.

### LINKED ISSUE #2926: Exception: Sequence contains more than one element
## Description

In version 2.2.3 there is a regression (compared to 2.1.2) for this code:

```c#
[TestClass]
public sealed class MyTestClass : MyTestClassBase
{
    [TestMethod]
    [TestCategory("MyTests")]
    public new void TestSomething()
    {
        base.TestSomething();
    }
}

public abstract class MyTestClassBase
{
    protected void TestSomething()
    {
        // Do something
    }
}
```

Executing this via:

```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "MyTests.dll" /TestCaseFilter:"TestCategory=MyTests"
```

Leads to this error (I had to manually translate it because the error is in German on my machine):

```
Exception in call of Executor "executor://mstestadapter/v2": The sequence contains more than one element.
```

This does not happen in version 2.1.2.

## Steps to reproduce

1. Create a modern-SDK test project
1. Select `net48` as target framework
1. Add code above
1. Reference NuGet packages like this:

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.3" />
```

Run the tests via `vstest.console` (like shown above).

## Expected behavior

There should be no exception.

## Actual behavior

The exception above is thrown.

## Environment

* Windows 10
* Visual Studio 2019 16.7.12
* vstest.console 16.7.0

[AB#1335565](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1335565)

### PR DESCRIPTION
**Pull request by Haplois**
Our FQN API is finalized, this PR makes it compliant with Visual Studio.

 - [x] Hierarchy order reversed to make it easily expandable. Currently, we only support 4 levels.
 - [x] Hierarchy API revised to return all 4 levels which are: `Test group`, `class name`, `namespace`, and `container`.
 - [x] `Test group` by default is managed method name without adapters.
 - [x] Fixes #2926

Hierarchies are for display purposes; we need to change how we generate those:
 - [x] Switch to using closed types instead of open. `TestMethod<string>` instead of ```TestMethod`1```.
 - [x] Append method parameters to `Test group` if any, do not append `()` if not.
 - [x] `Namespace` can be `string.Empty` in case of no namespace. Make sure that works as expected, and we're able to resolve when provided.

# Breaking changes
 - Hierarchy generation changed, RFC to be updated to reflect this. (https://github.com/microsoft/vstest-docs/pull/261)
 - Although this breaks compatibility with older versions of `Hierarchy` since those versions were officially released and never used by anyone - support will start with the first version we release. It will be bound to TP version, and adapter version. Check is done inside Test Explorer.

### CODE REVIEW

File: CODEOWNERS [hunk 1]
```diff
@@ -3,6 +3,11 @@
 PublicAPI.Shipped.txt @nohwnd @MarcoRossignoli
 PublicAPI.Unshipped.txt @nohwnd @MarcoRossignoli
 
+# Changes here might break our contracts with other adapters, and possibly
+# Visual Studio. 
+/src/Microsoft.TestPlatform.AdapterUtilities/ @haplois
```
Comment (Evangelink) [inline CODEOWNERS:8]: Shall we have a backup in case you are not around @Haplois?

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs [hunk 2]
```diff
@@ -119,11 +118,11 @@ public static void GetManagedName(MethodBase method, out string managedTypeName,
         var methodBuilder = new StringBuilder();
 
         // Namespace and Type Name (with arity designation)
+        // hierarchyPos contains [startIndexOfNamespace, endIndexOfNameSpace, endIndexOfTypeName]
         var hierarchyPos = AppendTypeString(typeBuilder, semanticType, closedType: false);
-        if (hierarchyPos is null || hierarchyPos.Length != HierarchyConstants.Levels.TotalLevelCount)
+        if (hierarchyPos is null || hierarchyPos.Length != 3)
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:123]: Could we avoid magic numbers? At least add some comment to explain how you get this number.

**Comment by nohwnd** [comment]
Can you add more info to the PR description please?

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs [hunk 3]
```diff
@@ -265,7 +266,17 @@ bool Filter(MemberInfo mbr, object? param)
...
+        if (methods.Length == 1)
+        {
+            method = (MethodInfo?)methods[0];
+        }
+        else if (methods.Length > 1)
+        {
+            method = (MethodInfo?)methods.SingleOrDefault(i => i.DeclaringType == type);
+        }
+
+        return method;
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:279]: Nit: Switch pattern would be easier to read. I am suggesting something without having tested it so there might be some small fixes to do:

```suggestion
        return methods.Length switch        
        {
            1 => (MethodInfo?)methods[0],
            > 1 =>(MethodInfo?)methods.SingleOrDefault(i => i.DeclaringType == type),
            _ => null,
        };
```

File: src/Microsoft.TestPlatform.AdapterUtilities/TestIdProvider.cs [hunk 4]
```diff
@@ -31,8 +31,27 @@ public void AppendString(string str)
         {
             throw new InvalidOperationException();
         }
+        if (str == null)
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.AdapterUtilities/TestIdProvider.cs:34]: Method signature should be updated to allow null: `string? str`.

File: src/Microsoft.TestPlatform.AdapterUtilities/HierarchyConstants.cs [hunk 5]
```diff
@@ -26,16 +26,42 @@ public static class Levels
         /// <summary>
         /// Total length of Hierarchy array.
         /// </summary>
-        public const int TotalLevelCount = 2;
+        /// <remarks>
+        /// Currently the order for this is usually:
+        /// <c>Managed Method Name</c>, <c>ClassName</c>, <c>Namespace</c>, <c>Assembly Display Name</c>.
+        /// </remarks>
+        public const int TotalLevelCount = 4;
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.AdapterUtilities/HierarchyConstants.cs:33]: Is it ok to merge these breaking changes now?

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs [hunk 6]
```diff
@@ -86,8 +86,7 @@ public static void GetManagedName(MethodBase method, out string managedTypeName,
 
         if (!ReflectionHelpers.IsMethod(method))
         {
-            // TODO: @Haplois, exception expects a message and not a param name.
-            throw new NotSupportedException(nameof(method));
+            throw new ArgumentException(Resources.Resources.ErrorMethodExpectedAsAnArgument, nameof(method));
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:89]: Could we add test for this case?

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs (hunk 2 above)
Comment (Haplois) [reply src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:123]: See line 121 :)

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs [hunk 7]
```diff
@@ -119,11 +118,11 @@ public static void GetManagedName(MethodBase method, out string managedTypeName,
...
 
         // Namespace and Type Name (with arity designation)
+        // hierarchyPos contains [startIndexOfNamespace, endIndexOfNameSpace, endIndexOfTypeName]
         var hierarchyPos = AppendTypeString(typeBuilder, semanticType, closedType: false);
-        if (hierarchyPos is null || hierarchyPos.Length != HierarchyConstants.Levels.TotalLevelCount)
+        if (hierarchyPos is null || hierarchyPos.Length != 3)
         {
-            // TODO: @Haplois, exception expects a message and not a param name.
-            throw new NotSupportedException(nameof(method));
+            throw new ArgumentException(Resources.Resources.ErrorMethodExpectedAsAnArgument, nameof(method));
```
[the remark this answers is not in the document]
Comment (Haplois) [reply src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:125]: Nope, I don't know how to create that state, as long as we get a method that will never happen. If we don't get a method, then we err out earlier.

File: src/Microsoft.TestPlatform.AdapterUtilities/HierarchyConstants.cs (hunk 5 above)
Comment (Haplois) [reply src/Microsoft.TestPlatform.AdapterUtilities/HierarchyConstants.cs:33]: Yes, our contract with Visual Studio and adapters is changing.

File: src/Microsoft.TestPlatform.AdapterUtilities/PublicAPI/PublicAPI.Shipped.txt [hunk 8]
```diff
@@ -1,9 +1,11 @@
 #nullable enable
 const Microsoft.TestPlatform.AdapterUtilities.HierarchyConstants.HierarchyLabel = "Hierarchy" -> string!
 const Microsoft.TestPlatform.AdapterUtilities.HierarchyConstants.HierarchyPropertyId = "TestCase.Hierarchy" -> string!
-const Microsoft.TestPlatform.AdapterUtilities.HierarchyConstants.Levels.ClassIndex = 1 -> int
-const Microsoft.TestPlatform.AdapterUtilities.HierarchyConstants.Levels.NamespaceIndex = 0 -> int
-const Microsoft.TestPlatform.AdapterUtilities.HierarchyConstants.Levels.TotalLevelCount = 2 -> int
+const Microsoft.TestPlatform.AdapterUtilities.HierarchyConstants.Levels.ContainerIndex = 0 -> int
+const Microsoft.TestPlatform.AdapterUtilities.HierarchyConstants.Levels.NamespaceIndex = 1 -> int
```
Comment (nohwnd) [inline src/Microsoft.TestPlatform.AdapterUtilities/PublicAPI/PublicAPI.Shipped.txt:5]: So how does this work when adapter utilities on testhost side and on IDE side are different? How do we keep compatibility with MSTest that is currently using this, like 2.2.9?

File: src/Microsoft.TestPlatform.AdapterUtilities/Resources/Resources.Designer.cs [hunk 9]
```diff
@@ -1,157 +1,163 @@
...
-        {
-            get
-            {
+        internal static string ErrorTypeNotFound {
+            get {
                 return ResourceManager.GetString("ErrorTypeNotFound", resourceCulture);
             }
         }
-
+
```
Comment (nohwnd) [inline src/Microsoft.TestPlatform.AdapterUtilities/Resources/Resources.Designer.cs:135]: Can the generator no emit these whitespace empty lines?

**Review by nohwnd — COMMENTED** [review]
My main concern is about breaking backwards compatibility. What is the consequences of that?

File: src/Microsoft.TestPlatform.AdapterUtilities/Resources/Resources.Designer.cs (hunk 9 above)
Comment (Haplois) [reply src/Microsoft.TestPlatform.AdapterUtilities/Resources/Resources.Designer.cs:135]: Idk, I'll check.

File: src/Microsoft.TestPlatform.AdapterUtilities/PublicAPI/PublicAPI.Shipped.txt (hunk 8 above)
Comment (Haplois) [reply src/Microsoft.TestPlatform.AdapterUtilities/PublicAPI/PublicAPI.Shipped.txt:5]: Yes, we will only enable this on next release. (That part is not baked in TE yet.) Also if an adapter returns something not supported we will fallback to current behavior.

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:156]: Is it worth transforming this into some `InvalidOperationException` then? It usually represents some invalid state (which seems to match this case).

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs [hunk 10]
```diff
@@ -81,20 +81,50 @@ public static void GetManagedName(MethodBase method, out string managedTypeName,
...
+    /// The hierarchy values.
+    /// </returns>
+    public static string[] GetManagedHierarchy(MethodBase method)
+    {
+        GetManagedNameAndHierarchy(method, true, out _, out _, out var hierarchyValues);
+
+        return hierarchyValues;
+    }
+
+    private static void GetManagedNameAndHierarchy(MethodBase method, bool useClosedTypes, out string managedTypeName, out string managedMethodName, out string[] hierarchyValues)
```
Comment (Evangelink) [inline src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:114]: It's not entirely clear to me what is a "closed type", could you please either explain here or add comment on one of the methods?

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs (hunk 6 above)
Comment (Evangelink) [reply src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:120]: It seems that test for this case is missing.

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs (hunk 10 above)
Comment (Haplois) [reply src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:114]: Yes. 'List<string>' is a closed type; and 'List<T>' is open.

**Review by Evangelink — COMMENTED** [review]
One last comment.

PS: It'd be better to have a separate PR for the assemblyinfo changes as they do not relate to this change.

File: src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs [hunk 11]
```diff
@@ -352,7 +399,9 @@ private static void AppendNamespace(StringBuilder b, string? namespaceString)
         }
     }
 
-    private static void AppendMethodString(StringBuilder methodBuilder, string name, int methodArity)
+#pragma warning disable IDE0060 // Remove unused parameter
+    private static void AppendMethodString(StringBuilder methodBuilder, string name, int methodArity, bool closedType)
```
[the remark this answers is not in the document]
Comment (Haplois) [reply src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/ManagedNameHelper.Reflection.cs:403]: I broke those in this PR - reverted them back. But for some reason it is shown as a change. It isn't :)

**Review by nohwnd — APPROVED** [review]
Approving, because I am promised we can iterate on the design. And hopefully make the values separate properties that will be output only when they have non-default values. And same for the FQN properties, because keeping them custom (in property bag) adds a lot of overhead.
